#!/usr/bin/python

HEARTBEAT_NAME   = "mail-poller"

DB_NAME          = ""  # BLANKED
DB_USER          = ""  # BLANKED
DB_HOST          = ""  # BLANKED
DB_PASS          = ""  # BLANKED

PUB_CHANNEL      = "tw:event:identity_poll"
SLEEP_TIME       = 12  # In seconds

SELECT_IID_QUERY = ("SELECT iid FROM identities WHERE"
                    " enabled AND verified ORDER BY iid DESC")
#SELECT_IID_QUERY = ("SELECT iid FROM identities WHERE"
#                    " enabled AND verified AND in_use ORDER BY random()")

import os
import psycopg2
import psycopg2.extras
import redbeat
import redis
import socket
import time


def main():
    redbeat.start_redbeat(
        HEARTBEAT_NAME, "{}/{}".format(socket.gethostname(), os.getpid()))

    conn = psycopg2.connect(
        dbname=DB_NAME, user=DB_USER, host=DB_HOST, password=DB_PASS)
    cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    redis_conn = redis.Redis()

    while True:
        cur.execute(SELECT_IID_QUERY)
        iids = cur.fetchall()

        for (iid,) in iids:
            time.sleep(SLEEP_TIME)
            redis_conn.publish(PUB_CHANNEL, str(iid))


if __name__ == '__main__':
    main()

