#!/usr/bin/python

import asyncore, socket, sys

class PromptClient(asyncore.dispatcher):

    def __init__(self, prompt):
        asyncore.dispatcher.__init__(self)
        self.create_socket(socket.AF_INET, socket.SOCK_STREAM)
        self.connect( ('localhost', 5080) )
        self.buffer = prompt

    def handle_connect(self):
        pass

    def handle_error(self):
        raise

    def handle_close(self):
        try:
            self.close()
        except:
            pass

    def handle_read(self):
        print self.recv(8192).rstrip()
        self.close()

    def writable(self):
        return (len(self.buffer) > 0)

    def handle_write(self):
        sent = self.send(self.buffer)
        self.buffer = self.buffer[sent:]


try:
    client = PromptClient(' '.join(sys.argv[1:]))
except:
    sys.stderr.write("Unable to open client!")
    sys.exit(1)

try:
    asyncore.loop()
except KeyboardInterrupt:
    sys.exit()
except socket.error:
    sys.stderr.write("ERROR: Couldn't connect to socket!\n")
    sys.exit(1)

